### ISSUE TITLE
Update Keynote talk times

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#10]
Currently live Q&A times are:

- Yoshua Bengio: 11:10 - 11:30am on Thursday, July 23
- Elaine Nsoesie: 1:40pm - 2:00pm ET on Thursday, July 23
- Nigam Shah: 2:00pm - 2:20pm ET (11:00am - 11:20am PT) on Thursday, July 23
- Sherri Rose: 11:10 - 11:30am ET on Friday, July 24
- Ruslan Salakhutdinov: 1:40pm - 2:00pm ET on Friday, July 24

**Comment by corcra** [comment]
This seems to have been done
