### ISSUE TITLE
Add entry point for navigating pre-recorded material

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#11]
Needs to include:

- [ ] Info about Zoom
- [ ] Info about SlidesLive
- [ ] Info about RocketChat
- [x] Recommended viewing schedule

This page should cover all the information in the email that @corca is sending to attendees. Perhaps some of this information could go into the FAQ page?

**Comment by mghassem** [comment]
Text potentially is:

All sessions are meant to be interaction Q/A with authors, and most will have pre-recorded talk/tutorial presentations that should be viewed prior to attending the Zoom sessions.

For all content other than tutorials and socials, there will be a single Zoom webinar link for the entire conference for both days. Registered participants will receive a password for the webinar session.

Tutorials and socials will have separate Zoom links, and passwords for these sessions will again be emailed to registered participants.

When you move from the main conference Zoom webinar to a tutorial session or social, leave the main conference webinar session and rejoin.

Please do not share/tweet/post any passwords, as sessions are likely to be Zoom-bombed if these are leaked.

Realtime questions and coordination can be done over RocketChat.
