### ISSUE TITLE
Update "Highlighted Papers" for "Research Paper Talks"

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#12]
Specifically, rename "Highlighted Papers" to "Research Paper Talks # - #" and add a second section for the second session each day.

**Comment by tnaumann** [comment]
Adding a note that preference is to order sessions by time rather than group by type; i.e., for Thursday it would be ordered as:

- Keynote Speaker 1
- Research Talks 1 - 6
- Research Talks 7 -12
- Keynote Speaker 2
- Keynote Speaker 3

Instead of 

- Keynote Speakers (all speakers)
- Highlighted Papers (all papers)

**Comment by corcra** [comment]
Given the new format for the schedule pages, I would suggest we entirely remove "highlighted papers" from the bottom of Thursday/Friday - this is easy to do if desired.

**Comment by corcra** [comment]
Removed in https://github.com/acm-chil/acm-chil-website/commit/cbc720d0cb1ecd1f5378f79314766543562c1fff
