### ISSUE TITLE
Updating Single-Day Schedules (Thursday/Friday) To Be Chronological Ordering/Tabular Format

### ISSUE THREAD

**Issue by mghassem** [acm-chil/acm-chil-website#17]
Can we modify the Thursday and Friday tabs to be chronological ordering?

Ideally, this would be:
Session Time (EST), Content Type (Tutorial, Keynote, Doctoral Symposium, Research Talk, Workshop Talk), Title (Paper/Talk Title, or "Doctoral Symposium"), Session Speaker Name(s), CHIL Moderator Name(s), Content Page Link, Zoom Session Link
<vbar>

The blurb for interaction:
"All sessions are meant to be interaction Q/A with authors, and most will have pre-recorded talk/tutorial presentations that should be viewed prior to attending the Zoom sessions. 

For all content other than tutorials and socials, there will be a single Zoom webinar link for the entire conference for both days. Registered participants will receive a password for the webinar session. 

Tutorials and socials will have separate Zoom links, and passwords for these sessions will again be emailed to registered participants. 

When you move from the main conference Zoom webinar to a tutorial session or social, leave the main conference webinar session and rejoin. 

Please do not share/tweet/post *any* passwords, as sessions are likely to be Zoom-bombed if these are leaked. 

Realtime questions and coordination can be done over RocketChat.
"

The actual daily content for THURSDAY is:
------------
10:00 AM - 10:50 AM (EST) | Tutorial | A Tour of Survival Analysis, from Classical to Modern  | George H. Chen, Jeremy C. Weiss  | Irene Chen |  LINK HERE | TutorialZoomLink
<vbar>
10:00 AM - 10:50 AM (EST) | Tutorial | Medical Imaging with Deep Learning | Joseph Paul Cohen | Irene Chen |  LINK HERE | TutorialZoomLink
<vbar>
10:00 AM - 10:50 AM (EST) | Tutorial | Public Health Datasets for Deep Learning: Challenges and Opportunities | Ziad Obermeyer, Katy Haynes, Josh Risley | Irene Chen |  LINK HERE | TutorialZoomLink
<vbar>
11:00 AM - 11:10 AM | Introduction | Opening Remarks | Marzyeh Ghassemi | TBD | N/A  | MainZoomLink
<vbar>
11:10 AM - 11:30 AM | Keynote | Title Here | Yoshua Bengio | Tristan Naumann |  Link | MainZoomLink
<vbar>
10:00 AM - 10:05 AM | Research Talk | Defining Admissible Rewards for High-Confidence Policy Evaluation in Batch Reinforcement Learning | Niranjani Prasad | TBD | Link | MainZoomLink
<vbar>
10:05 AM - 10:10 AM | Research Talk | Variational Learning of Individual Survival Distributions | Zidi Xiu | TBD | Link | MainZoomLink
<vbar>
10:10 AM - 10:15 AM | Research Talk | Interpretable Subgroup Discovery in Treatment Effect Estimation with Application to Opioid Prescribing Guidelines | Chirag Nagpal | TBD | Link | MainZoomLink
<vbar>
10:15 AM - 10:20 AM | Research Talk | Adverse Drug Reaction Discovery from Electronic Health Records with Deep Neural Networks | Wei Zhang | TBD | Link | MainZoomLink
<vbar>
10:20 AM - 10:25 AM | Research Talk | CaliForest: Calibrated Random Forest for Health Data | Yubin Park | TBD | Link | MainZoomLink
<vbar>
10:25 AM - 10:30 AM - 10:25 AM | Research Talk | BMM-Net: Automatic Segmentation of Edema in Optical Coherence Tomography Based on Boundary Detection and Multi-Scale Network | Ruru Zhang | TBD | Link | MainZoomLink

12:00 PM - 11:00 PM (EST) | Social Lunch | Social Lunch | N/A | Irene Chen |  N/A | SocialZoomLink
<vbar>

1:00 PM - 1:10 PM | Introduction | Welcome Back | Marzyeh Ghassemi | TBD | N/A  | MainZoomLink

<vbar>
>>> PUT IN DETAILS FOR Paper Talks 7 - 12 
>Research Talk 7 
Survival Cluster Analysis
Paidamoyo Chapfuwa

>Research Talk 8 
An Adversarial Approach for the Robust Classification of Pneumonia from Chest Radiographs
Joseph D. Janizek

>Research Talk 9 
Explaining an increase in predicted risk for clinical alerts
Michaela Hardt

>Research Talk 10
Fast Learning-based Registration of Sparse 3D Clinical Images
Kathleen Lewis 

>Research Talk 11
Multiple Instance Learning for Predicting Necrotizing Enterocolitis in Premature Infants Using Microbiome Data
Thomas Hooven 

>Research Talk 12
Hurtful Words: Quantifying Biases in Clinical Contextual Word Embeddings
Haoran Zhang

1:40 PM - 2:00 PM | Keynote | Title Here | Elaine Nsoesie | TBD |  Link | MainZoomLink
<vbar>
2:00 PM - 2:20 PM | Keynote | Title Here | Nigam Shah | TBD |  Link | MainZoomLink
<vbar>
2:20 PM - 2:30 PM | Introduction | Day 1 Closing Remarks | Marzyeh Ghassemi | TBD | N/A  | MainZoomLink

**Comment by tompollard** [comment]
@mghassem the functionality to display this information is now ready (e.g. see: https://www.chilconference.org/calendar.html#tab-thu). 

Please could someone add the schedule to the following file?: https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/daytoview.yml

The times in the post above seem to be mixed up (10am reappears after 11am), so this schedule needs a review before adding!

**Comment by mghassem** [comment]
Thanks @tompollard !

Could we modify to:
0) Remove the "Read More" Column.
1) Change the "Video link" Column to be "Session Link".
2) Include two link fields for A) the session docpage and B) the session Zoom link.
3) Make the "Title" Column text link to the specified session docpage link.
4) Make the "Session Link" Column text link to the specified Zoom link.

**Comment by tompollard** [comment]
Sure. Just see you can see how this works (and tweak if necessary), the [components.html file](https://github.com/acm-chil/acm-chil-website/blob/master/templates/components.html) includes the following macro:

```python
{% macro day_to_view(day) -%}
<div class="cards row">
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Time</th>
      <th scope="col">Type</th>
      <th scope="col">Title</th>
      <th scope="col">Speaker</th>
      <th scope="col">Moderator</th>
      <th scope="col">Read more</th>
      <th scope="col">Video link</th>
    </tr>
  </thead>
    <tbody>
    {% for row in day %}
    <tr>
      <td>{% if row.time %}{{ row.time }}{% endif %}</td>
      <td>{% if row.type %}{{ row.type }}{% endif %}</td>
      <td>{% if row.title %}{{ row.title }}{% endif %}</td>
      <td>{% if row.speaker %}{{ row.speaker }}{% endif %}</td>
      <td>{% if row.moderator %}{{ row.moderator }}{% endif %}</td>
      <td>{% if row.doclink %}{{ row.doclink }}{% endif %}</td>
      <td>{% if row.videolink %}{{ row.videolink }}{% endif %}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
</div>
{%- endmacro %}
```

This iterates the yaml content (which is loaded as a python dictionary) and creates the HTML that you see at: https://www.chilconference.org/calendar.html#tab-thu

So the template just needs modifying so that the link variables (e.g. `{{ row.doclink }}`) are included in `href` tags.

**Comment by tompollard** [comment]
@mghassem I've updated the template. We now have the following fields in the YAML file:

```
  - time: "10:00 AM - 10:50 AM"
    type: Tutorial 
    title: A Tour of Survival Analysis, from Classical to Modern 
    speaker: George H. Chen, Jeremy C. Weiss  
    moderator: Irene Chen 
    doclink:
    sessionlink: 
    sessionlinktext: Coming soon
```

- If there is a `doclink`, then this will be linked to the title.
- If there is a `sessionlink` then this will be linked to the `sessionlinktext`. 

Hope this helps!
