### ISSUE TITLE
Creating a Recommended Viewing Schedule Tab

### ISSUE THREAD

**Issue by mghassem** [acm-chil/acm-chil-website#18]
Separately from the the actual interactive schedule, we should provide a recommended viewing schedule that can be linked to, which we can email out to the participants. 

Tasmie's suggested schedule for Wednesday (before Thursday sessions) is:

Time | Title | SlidesLive Link
-------
10 min. | Making the most of CHIL |  LINK
20 min. | Keynote 1 | Yoshua Bengio
48 min. | Research Paper Talks 1 - 6 | Various authors
12 min. | (Break) | N/A
48 min. | Research Paper Talks 7 - 12 | Various authors
12 min. | (Break) | N/A
20 min. | Keynote 2 | Elaine Nsoesie
20 min. | Keynote 3 | Nigam Shah
39 min. | Workshop Spotlights 1 - 13 | Various authors
10 min. | (Break) | N/A
30 min. | Tutorial Session 1 | N/A
  | └ Tutorial 1 | Ziad Obermeyer, Katy Haynes, Josh Risley
  | └ Tutorial 2 | George Chen, Jeremy Weiss
  | └ Tutorial 3 | Joseph Paul Cohen

Suggested schedule for Thursday evening (before Friday sessions) is:

Time | Title | SlidesLive Link
-------
20 min. | Keynote 4 | Sherri Rose
48 min. | Paper Talks 13 - 18 |  Links
12 min. | (Break) |  
48 min. | Paper Talks 19 - 23 |  Links
12 min. | (Break) |  
20 min. | Keynote 5 | Ruslan
39 min. | Workshop Spotlights 14 - 26 |  Links
30 min. | Tutorial Session 2 |  
  | └ Tutorial 4 |  
  | └ Tutorial 5 |  
30 min. | Doctoral Symposia Talks | Links

**Comment by tompollard** [comment]
I'll take a look at this now.

**Comment by tompollard** [comment]
I have added the details to a "Recommended viewing" tab at: https://www.chilconference.org/calendar.html#tab-preview. It might be worth adding a little more explanatory text at the top of the page.

@mghassem please take a look and let me know if it looks okay. I dropped the breaks, because it felt strange having them in a schedule that people are unlikely to watch right from start to finish.

**Comment by tompollard** [comment]
Instead of "Recommended viewing", I wonder whether something like "Pre-recorded talks" might be clearer?

**Comment by mghassem** [comment]
I think we want to indicate that this is only the order we recommend that they go in somehow? We could do "Recommended Ordering of Pre-Recorded Talks for Conference Interactive Sessions"?
