### ISSUE TITLE
Inconsistent timezone updates

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#22]
Currently the calendar updates based on the timezone in which the schedule is viewed (https://www.chilconference.org/calendar.html#tab-calendar). However the other tabs, e.g. [Thursday](https://www.chilconference.org/calendar.html#tab-thu) and [Friday](https://www.chilconference.org/calendar.html#tab-fri) do not.

Low priority, but has created some confusion with times overlapping. Easy fix might be to indicate that all times are ET.

**Comment by tompollard** [comment]
@mghassem @tnaumann should we just remove https://www.chilconference.org/calendar.html#tab-calendar ?

It's just one additional thing to keep updated, and I'm not sure that it adds any value.

**Comment by mghassem** [comment]
I would. :l

**Comment by tompollard** [comment]
Okay, the calendar tab is no more!: https://www.chilconference.org/calendar.html. 

@tnaumann does this address the issue?

**Comment by tnaumann** [comment]
Yes, this resolves the issue.
