### ISSUE TITLE
Clarify that schedule refers to live Q&A

### ISSUE THREAD

**Issue by corcra** [acm-chil/acm-chil-website#24]
Related to #18 , #17, #11.

Right now a naive observer won't realise the schedule (e.g. https://www.chilconference.org/calendar.html#tab-thu) refers only to live Q&A sessions.

I suggest we add a line at the top of the schedule pages to the effect of

"The following schedule refers to live Q&A sessions. All talks will be pre-recorded and should be watched prior to the Q&A sessions - see [link to recommended viewing page] for a recommended order of viewing, and links to the pre-recorded content. You can pre-submit questions for the Q&As on RocketChat [link]."

**Comment by tompollard** [comment]
I agree this is needed. Currently it's not really clear how https://www.chilconference.org/calendar.html#tab-preview relates to the other schedules.

**Comment by alistairewj** [comment]
So we had a bit of a conversation about this and we thought the schedule page could be reorganized as follows:

- Add a "Guidance" tab at the far left explaining the general conference flow
- Rename "Recommended Viewing" to "Prerecorded Content" or something similar.
  - This will contain all the links to the SlidesLive content
  - Consider dropping the "Thursday" and "Friday" sub-headings
  - Add a column which indicates the live Q&A session time
- At the top of Thursday/Friday, a brief description which mentions viewers can watch find pre-recorded content on the other page

We also need to add RocketChat links to rows as appropriate.

**Comment by tompollard** [comment]
I added a guidance tab (https://www.chilconference.org/calendar.html) with the high-level overview we discussed:

> The conference is broadly organized into:
> - Pre-recorded presentations, available for viewing anytime after 21 July 2020.
> - RocketChat channels to enable focused discussion around presentations.
> - Live Zoom sessions for Q&A and social events.

**Comment by mghassem** [comment]
Done.
