### ISSUE TITLE
Specify time-zone in calendar

### ISSUE THREAD

**Issue by corcra** [acm-chil/acm-chil-website#25]
Pages with times (e.g. https://www.chilconference.org/calendar.html#tab-thu), should specify that times are EDT.

**Comment by tasmie** [comment]
Eastern Time (GMT-5)

**Comment by tnaumann** [comment]
@corcra / @tasmie check to see that this is sufficient and close if so.

**Comment by tasmie** [comment]
@tnaumann I like how EDT is under Time on the Thursday schedule instead of beside it on the Friday schedule
