### ISSUE TITLE
Indicate URL for Rocket Chat so that desktop client can be used.

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#30]
Some users may be using the Rocket Chat desktop client. This requires a web URL to be specified in order to join.

For testing, I'm using Homebrew-based installation
```
[[ $(command -v brew) == "" ]] && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew cask install rocket-chat
```

**Comment by mghassem** [comment]
Done on the guidance page in Schedule.

**Comment by tnaumann** [comment]
Perfect. I was able to successfully connect from desktop client.
