### ISSUE TITLE
Remove random ACM logo on the home page banner

### ISSUE THREAD

**Issue by tasmie** [acm-chil/acm-chil-website#32]

**Comment by corcra** [comment]
If you mean the one below the "Register now!" button, it's actually part of the background image somehow. We'll need to find the original version of that image. (Just commenting this here cause I don't have time to do that right now, but maybe someone else can).

**Comment by tnaumann** [comment]
@tasmie / @mghassem - do you have a copy of this image without the ACM logo?

**Comment by tasmie** [comment]
@tnaumann  https://upload.wikimedia.org/wikipedia/commons/d/dc/Shiny_buildings_in_Toronto.jpg
