### ISSUE TITLE
Add SlidesLive links for pre-recorded content

### ISSUE THREAD

**Issue by corcra** [acm-chil/acm-chil-website#35]

**Comment by corcra** [comment]
Waiting for links in spreadsheet.

**Comment by tnaumann** [comment]
Which SlidesLive links are you waiting on? I added these all to the various .csv files last week?

**Comment by corcra** [comment]
I've made a "pivoted" version of the contents page which groups by content type (e.g. keynote, tutorial, etc.) so we can list every individual paper, it looks like this:
![image](https://user-images.githubusercontent.com/4471845/87980974-5ebff900-cacc-11ea-94ec-5fc5da2dda02.png)

It's in this branch:
https://github.com/acm-chil/acm-chil-website/tree/alt_content

@mghassem or @tnaumann what do you think?

**Comment by corcra** [comment]
I am aware that this page is increasingly just duplicating the contents of the Thurs/Fri schedule pages, but I also think it's fine to give people two "views" of the schedule - one which starts from pre-recorded content and tells you when the Q&A session will be, and another which is ordered by the chronology of the Q&A sessions.

**Comment by tnaumann** [comment]
I think this is pretty cool for the pre-recorded content page. The Thu/Fri pages primarily link through to Live Q&A, so this is a great way to navigate the content.
