### ISSUE TITLE
Add RocketChat with corresponding channel

### ISSUE THREAD

**Issue by corcra** [acm-chil/acm-chil-website#36]
- [ ] Tutorials

- [ ] Keynotes

- [ ] Research talks

**Comment by mmcdermott** [comment]
My understanding for this is that we'll need to (1) Modify https://github.com/acm-chil/acm-chil-website/blob/master/templates/components.html#L262 to eliminate the `paper_` in front of the link (in favor of just using the raw ID, as we didn't name everything starting with `paper_`, then (2) update the CSVs: https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/tutorials.csv, https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/papers.csv, and https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/workshops.csv, respectively (we didn't, I believe, make rocketchat rooms for keynotes), adding the full channel name in the rocketchat_id column. @corcra or @tompollard, does that sound right to you? Wanted to confirm before I begin editing anything. @alistairewj FYI.

**Comment by corcra** [comment]
That sounds reasonable @mmcdermott! I would say just build it locally and test that it works, you won't break anything :)

**Comment by mmcdermott** [comment]
#46 solves this.

**Comment by corcra** [comment]
This is merged now, thanks @mmcdermott !
