### ISSUE TITLE
Swap speaker names based on registration

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#40]
From @tasmie:

Thursday:
- [x] Thomas Hoovan with Ansaf Salleb-Aouissi  

Friday
- [x] Shaun Gupta with Patrick Long 
- [x] Eric Lee with Byron Wallace or Joyce Ho
- [x] Luke Oakden with Jared Dunnmon 
- [x] Luke Oakden with Joyce Ho or Ioakeim Perros

**Comment by tasmie** [comment]
Thomas Hoovan with Ansaf Salleb-Aouissi - **not needed, Thomas registered.** 

 Shaun Gupta with Patrick Long 
 Eric Lee with Byron Wallace or Joyce Ho - **not needed, Eric is registered**
 Luke Oakden with Jared Dunnmon
 Luke Oakden with Joyce Ho or Ioakeim Perros

**Comment by tnaumann** [comment]
Thanks, @tasmie. I'll make the remaining changes now.

**Comment by tnaumann** [comment]
Actually, sorry. @tasmie can you clarify what papers these are for? Several of these names don't show up in the https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/daytoview.yml where they would be changed.

**Comment by tasmie** [comment]
@tnaumann these are supposed to be Research Talks. Also just realized an error. See below for most updated: 

FRIDAY
Using SNOMED to automate... - done. Shaun was already replaced with Patrick
Hidden Stratification... replace Luke with Jared Dunnmon
TASTE: Temporal and static... replace Ardavan with Ioakeim Perros

**Comment by tnaumann** [comment]
@tasmie verify and close if correctly fixed.

**Comment by tasmie** [comment]
@tnaumann I can't figure out how to close these. According to Google there should be a box next to the comment but it doesn't show up for me, possibly because of my account settings? Anyway, this is closed!

**Comment by tnaumann** [comment]
Sorry, @tasmie! I think this is a permissions thing, but I don't have the permissions to expand your access :)
