### ISSUE TITLE
Keynote titles are missing 

### ISSUE THREAD

**Issue by corcra** [acm-chil/acm-chil-website#5]
See here: https://www.chilconference.org/calendar.html#tab-thu
For each keynote it just says "TITLE"

**Comment by tompollard** [comment]
Thanks @corcra. Abstracts also missing from the individual profile pages (e.g. https://www.chilconference.org/speaker_1.html). The solution is either:

- adding the details to: https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/speakers.csv 
- removing the title and abstract fields from the template.

**Comment by corcra** [comment]
I think we should add this info (and I'm happy to do so in a PR) but I don't know who has it!

**Comment by mghassem** [comment]
Added, except for Rus.
