### ISSUE TITLE
RocketChat is not displayed for Keynote and Doctoral Symposium Speakers

### ISSUE THREAD

**Issue by tompollard** [acm-chil/acm-chil-website#65]
I haven't looked into why, but the RocketChat window is not displayed on speaker pages for Keynotes and Doctoral Symposium Speakers. e.g.:

- Doctoral Symposium: https://www.chilconference.org/ds_a.html
- Keynote speaker: http://localhost:5000/speaker_2.html

**Comment by tnaumann** [comment]
Keynote is discussed in general, so perhaps it's not displayed because there's not a specific room / channel.

**Comment by tompollard** [comment]
It isn't obvious that keynote chat should be in the general channel.  For consistency with other sessions, and because I think focusing channels on the talks is nice, my preference would be to have dedicated channels for the keynotes too. Happy to stick with things as they are though!

**Comment by tompollard** [comment]
It looks like the RocketChat IDs are just not populated for Keynote speakers: https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/speakers.csv. Same for the Doctoral Symposium:  https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/dss.csv. If we are using the general channel, then presumably there is an ID for the channel that can be added.

**Comment by tompollard** [comment]
@mmcdermott @alistairewj not sure where i got this from, but in my mind you are the rocketchat people! any thoughts on the discussion above?

**Comment by mmcdermott** [comment]
yeah, we just need to add "general" as the rocketchat_id for keynotes and "doctoral_symposium" for DS talks. If someone wants to take this today, that'd be great, but if not I can pick it up this evening.

**Comment by corcra** [comment]
Pushed and deployed, let me know if there are further issues.

My inclination would also be to have dedicated channels for the keynotes simply because that's how it was at ICML afair. If we use #general we just need to make sure the keynotes are checking it for questions, I guess?
