### ISSUE TITLE
Guidance page - zoom info

### ISSUE THREAD

**Issue by tasmie** [acm-chil/acm-chil-website#68]
Change the first bullet text under Zoom heading to read: 

Each session as a dedicated zoom link. Visit the the Thursday and Friday schedule pages to to find the corresponding link to each live Q&A session.  
Registered participants will receive a single password on each day for the all sessions via email. For example, the password for all sessions Day 1 will be XXXXXX and the password for all sessions on Day 2 will be XXYYXX.
Please do not share/tweet/post any passwords, as sessions are likely to be Zoom-bombed if these are leaked.

**Comment by corcra** [comment]
Updated in https://github.com/acm-chil/acm-chil-website/commit/dd04b0d0a9cafee3d747914fc7abda3e2f2faf78
