### ISSUE TITLE
Highlight link for registration

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#7]
Currently the link to registration (http://www.cvent.com/d/knqpjz) can be difficult to spot. Consider replacing with a larger centered button that says "Register" and in turn links through to the cvent page.

**Comment by tompollard** [comment]
Stephanie added more prominent badges in https://github.com/acm-chil/acm-chil-website/pull/13. See the new register button on the front page for example: https://www.chilconference.org/

**Comment by tnaumann** [comment]
This is exactly what I had in mind! Thanks @corcra.
