### ISSUE TITLE
Add Zoom # to Friday

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#74]
Similar to the way that Thursday schedule has Zoom # can we add these to Friday? The specific number to add to each is in the minute by minute spreadsheet.

@corcra, hoping you can take a look at this in the AM to take advantage of time difference.

**Comment by corcra** [comment]
I've done this (#75) but as per my comment on #72, I copied Marzyeh's convention on Thursday and gave the tutorials 7A and 7B (to make it clear they're simultaneous), so it doesn't entirely match what's in the spreadsheet.
