### ISSUE TITLE
Add tab for Workshop Spotlights

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#8]
We should add a tab for the accepted workshop spotlights. Similar to Doctoral Symposium tab request.

**Comment by corcra** [comment]
@tnaumann (as per my response to #9) this is easy to add if we have the underlying CSV of the content - is this something you can create?

**Comment by corcra** [comment]
@mghassem Do you know who would be responsible for creating the CSV of the workshop content? This is the outstanding issue here I think

**Comment by corcra** [comment]
Just noticed this seems to already have been added (https://github.com/acm-chil/acm-chil-website/blob/master/sitedata/workshops.csv) - I missed this, can add the tab now

**Comment by tnaumann** [comment]
Appeared from the ether last week :)
