### ISSUE TITLE
Update bio for Regina Barzilay

### ISSUE THREAD

**Issue by tnaumann** [acm-chil/acm-chil-website#89]
Bio for Regina Barzilay should read:

Regina Barzilay is a professor in the Department of Electrical Engineering and Computer Science and a member of the Computer Science and Artificial Intelligence Laboratory at the Massachusetts Institute of Technology. She is an AI faculty lead for Jameel Clinic, an MIT center for  Machine Learning in Health at MIT. Her research interests are in natural language processing, applications of deep learning to chemistry and oncology. She is a recipient of various awards including the NSF Career Award, the MIT Technology Review TR-35 Award, Microsoft Faculty Fellowship and several Best Paper Awards at NAACL and ACL. In 2017, she received a MacArthur fellowship, an ACL fellowship and an AAAI fellowship. In 2020, she was awarded AAAI Squirrel Award for Artificial Intelligence for the Benefit of Humanity.  She received her Ph.D. in Computer Science from Columbia University, and spent a year as a postdoc at Cornell University. Regina received her undergraduate from Ben Gurion University of the Negev, Israel.

**Comment by getsarker** [comment]
Bio updated.
